---
- name: Run jcmd as nxportal user, capture PID and start JFR recording ("{{ JMCRunningTime }}" seconds)
  hosts: all
  become: true
  collections:
    - community.general
  tasks:
    - name: Run jcmd with shell module
      shell: "sudo -u nxportal jcmd"
      register: jcmd_output
    - name: Get process ID ending with SMALL
      shell: sudo -u nxportal jcmd | grep 'SMALL$' | awk '{print $1}'
      register: process_id_output
      changed_when: false
    - name: Extract process ID
      set_fact:
        process_id: "{{ process_id_output.stdout.split('\\n')[0] }}"
    - name: Start JFR recording with seconds duration
      shell: "sudo -u nxportal jcmd {{ process_id }} JFR.start duration={{ JMCRunningTime }}s filename=/home/nxportal/myrecording.jfr"
      when: process_id is defined
    - name: Wait for "{{ JMCRunningTime }}" seconds
      wait_for:
          timeout: "{{ JMCRunningTime }}"
    - name: Create destination directory (if required)
      become: false
      file:
        path: "{{ PlaybookPath }}/Result/{{ Job_id }}/{{ ansible_host }}/"  # Replace with your desired local path
        state: directory
        mode: 0755
      delegate_to: localhost
    - name: Specifying a path directly
      ansible.builtin.fetch:
        src: "/home/nxportal/myrecording.jfr"
        dest: "{{ PlaybookPath }}/Result/{{ Job_id }}/{{ ansible_host }}/Result_jmc.jfr"
        flat: yes



